### ISSUE TITLE
Documentation isn't available on docs.rs

### ISSUE THREAD

**Issue by FreeFull** [fdehau/tui-rs#1]
https://docs.rs/crate/tui/0.1.1/builds/35335 It seems the documentation isn't available there due to a build error involving termbox. It would be nice to have the documentation accessible online, rather than having to get the crate and build it with `cargo doc`

**Comment by fdehau** [comment]
Thanks for reporting the issue. It seems that the error comes from the custom build script used by the [termbox-sys](https://github.com/gchp/termbox-sys) crate. Maybe try to open an issue there since this documentation problem seems to affect all libraries relying on it. In the meantime, I may find a way to remove the need for [rustbox](https://github.com/gchp/rustbox) in the default build.

**Comment by cardoe** [comment]
https://docs.rs/crate/tui seems to work so this can probably be closed.
