### ISSUE TITLE
provide wrapped Terminal type in render() closures

### ISSUE THREAD

**Issue by cardoe** [fdehau/tui-rs#10]
So when implementing a full app it looks like the best practice is to implement different `draw()` functions that encompass each group of widgets. You end up calling each `draw()` inside the `render()` closure, e.g. https://github.com/fdehau/tui-rs/blob/b2bb24b9d21f71efd794896c4f7aae307d2f0eb5/examples/demo.rs#L283

I ended up implementing my example app by implementing my first group and having the top level app loop call its `draw()`. Then I put that group within another group and made a new `draw()` calling the original like linked above. But the program immediately stopped working and didn't show anything. I was really confused for a but but then realized that my inner `draw()` still had a `t.draw()` call which caused the issue. There was no error or panic, the application just sat there with an empty screen. Looking at `Terminal` there are a few things that look like they shouldn't be called at this inner level so maybe it'd be better to provide a wrapped type or a trait that just doesn't implement all these additional methods so people can't get tripped up by them.

**Comment by fdehau** [comment]
Hi, again you make a very good point. This behavior should be avoided in order to not confuse people starting with the library. I will look at it.

On the subject of best practices, I would also point out the fact that you could implement your own widgets, wrapping the ones provided by this crate. I will try to write about it somewhere or to provide a new version of the demo using this pattern.

**Comment by fdehau** [comment]
The last release of this crate (beta version for now) fixes this long standing issue. Widgets are rendered on a `Frame` instead of the `Terminal` directly.
