### ISSUE TITLE
Intersted in picture or video rendering implementation?

### ISSUE THREAD

**Issue by meteor-lsw** [fdehau/tui-rs#143]
I have tried to render an image and the results look good.

I have submitted the relevant example code #141 .

![深度截图_选择区域_20190313225513](https://user-images.githubusercontent.com/22556004/54288865-26103580-45e3-11e9-9755-aa7f65e4cc59.png)

Is there anyone else interested in rendering images or videos on the terminal? I think rendering at 240p resolution is feasible. If anyone else is interested in this topic, welcome to discuss and work towards this goal.

**Comment by longwusha** [comment]
![w3mimgpreview](https://user-images.githubusercontent.com/22556004/54326303-fd1e8d80-4640-11e9-89d1-24d34e034169.png)
![深度截图_选择区域_20190314094508](https://user-images.githubusercontent.com/22556004/54326357-263f1e00-4641-11e9-86a8-9989fd0264e4.png)

**Comment by fdehau** [comment]
Regarding, your two last examples I think those are high-res outputs are achieved using custom apis provided by some terminal emulators. Unless, one the backends in use within this crate supports it, it is unlikely that we will be able to reproduce them.

**Comment by cjbassi** [comment]
It seems like [sixel](https://en.wikipedia.org/wiki/Sixel) graphics are gaining in popularity as a way to display images in terminals, especially with the help of [libsixel](https://github.com/saitoha/libsixel) which even has a couple of rust api bindings. Sixel is already supported by a few terminals including xterm (with certain build flags), and there's an open issue for it in alacritty [here](https://github.com/jwilm/alacritty/issues/910). Someone has also been working on adding sixel support to termui [here](https://github.com/gizak/termui/pull/233).

**Comment by srlehn** [comment]
I think the first of the two example images is the ranger file manager displaying with w3mimgdisplay.
The second image seems to be sixel.

**Comment by samsieber** [comment]
I'm actually very interested in being able to display arbitrary image data, mostly from the image crate. That would make this crate very useful to me. I think I'm going to try using termion for now.

**Comment by EvanCarroll** [comment]
https://gitlab.redox-os.org/redox-os/termion/issues/180

**Comment by klamonte** [comment]
@samsieber

If you decide to implement sixel, then I wanted to pass on some things I've picked up recently, on the odd chance it could help.  (Even if just by way of "go check out notcurses, it's really cool." ;) )

I implemented sixel output in [my Java-language library](https://jexer.sourceforge.io/evolution.html#sixel) in late 2018.  For a while only xterm, RLogin, and yaft could handle the output without crashing.  I [reported on that work](https://gitlab.freedesktop.org/terminal-wg/specifications/-/issues/26#note_524831) in a terminal emulators forum, and several folks reported bugs in a few terminals.  Now [there are at least 10-20 terminals and terminal widgets that work well.](https://gitlab.com/klamonte/jexer/-/wikis/terminals)

Last week I added translucent windows with images under/over, thanks in large part to some clues from notcurses.  Some notes of that work are here: https://gitlab.com/klamonte/jexer/-/issues/88  .  I also wrote down more details on my particular mixed image-and-text cell model [here](https://gitlab.com/klamonte/jexer/-/wikis/high-level-design#text-cells) , with some narrative (and again the notcurses shoutouts) [here](https://jexer.sourceforge.io/evolution.html#year2021).

For encoding to sixel, check out notcurses' new [octree implementation](https://github.com/dankamongmen/notcurses/issues/2503) sometime.  It's very likely the fastest and highest-quality anywhere right now, at least for xterm-type terminals.  (libsixel was tested on real hardware, so that might give it an edge still in terms of compatibility.)

Depending on how you choose to render, you may find that 256-bit colors per sixel could still result in close to [16-bit apparent visual bit depth](https://gitlab.com/klamonte/jexer/-/raw/master/screenshots/snake_xterm_hq.png) on the actual screen, making the drive for non-sixel support a bit less crucial.  (Note that the best bit depth for sixel is 19.97 bits: 101^3.)  The screenshot link is my [very naive median-cut encoder](https://gitlab.com/klamonte/jexer/-/issues/87), which is much worse than notcurses' octree encoder -- but that's still good enough that you might not be able to tell when I'm using iTerm2+PNG vs sixel.

Finally, and to my utter surprise, I may have encountered an actual xterm bug: https://gitlab.com/klamonte/jexer/-/issues/89 .  Both foot and wezterm are doing quite well on sixel, and very nice options to have for testing.

All in all, I'm pretty happy with the possibilities from plain old sixel:

[xterm with translucency and animations](https://user-images.githubusercontent.com/4357501/149827860-30c45433-cf25-406c-8e4a-68a3b2d04f82.mp4)

**Comment by TurtleTheSeaHobo** [comment]
I've got a patch on my fork that currently allows sixels to work. Basically, you can currently just dump a string containing an encoded sixel into the symbol field of a cell and the backend will totally output it just fine. Just need to add a field to cells that allows them to elect to be skipped by the `Buffer::diff` method when generating updates. That way, a sixel widget covering a given area can have all the cells under the sixel be skipped so it doesn't get drawn over by space characters.

To bring sixels onto the `tui-rs` side, we'll want a couple things, though:
- a sixel implementation (e.g. `sixel-sys` or a custom one if we don't like FFI)
- some way to reliably figure out terminal dimensions in pixels

We'll want the sixel implementation in order to convert image data into encoded sixel strings, if we want to abstract that much away from the user. We'll also want to know the pixel dimensions of a cell so that we can resize the sixel (and underlying image data) to fit its allotted area, or at least inform the user of the dimensions they need to fill. Otherwise, there's no way for us or them to make sure that the sixel actually occupies the space it was allotted.

It would probably be responsible to put this under an optional feature, due to the extra dependencies and non-universal support. That said, sixels do enjoy much wider support than other formats and conceptually very simple. We might consider supporting other protocols too, but I think sixels are a good starting point.
![20220123_21h56m10s_grim](https://user-images.githubusercontent.com/41242296/150719531-71d3db09-89b3-4598-a8e4-9c58bc03c349.png)
The top left is the cell with the sixel encoded. A, B, and C are the other corners. Notice the bottom line has no sixel. It's part of the drawable region (B and C are the actual bottom line of my emulator), but the sixel will get scrolled back up a line if it tries to draw there. Seems implementations prefer to add an extra newline after every sixel just to make sure there's no overlap. Not sure if there's any way around it.

**Comment by TurtleTheSeaHobo** [comment]
Forgot to mention, I'm figuring out terminal dimensions by emitting an escape sequence (`<ESC>[14t`) and parsing stdin, but this isn't universal either. Neither termion or crossterm seem to support it, so this is a standing issue as well.

**Comment by klamonte** [comment]
You can also use CSI 16/18t to estimate the cell dimensions (# pixels / # cells). But it's unusual for a TE to support only one of 14/16/18 and not all of them.

**Comment by klamonte** [comment]
I found a trick to put sixel on the bottom row. It is standard, but some TEs don't do it right. https://gitlab.com/klamonte/jexer/-/issues/91

**Comment by TurtleTheSeaHobo** [comment]
![20220124_15h08m15s_grim](https://user-images.githubusercontent.com/41242296/150877986-c3a69c72-0673-4e74-a2e2-2f4d48af987c.png)
Awesome, looks like that did the trick! I'm looking at that octree sixel implementation now. For this project, I think it would be good to to have a native Rust implementation of sixel which could operate efficiently over a sparse set of image buffers. That way we can generate the screen-wide sixel we need in DECSDM.

**Comment by klamonte** [comment]
I've been horrible with polluting that thread with references so will stop doing that, but do check out [chafa's](https://github.com/hpjansson/chafa) implementation too (issue 27 "sixel support" over there, start at June 22, 2020).  It might be more readable / Rust-able, and today on some (maybe many?) image types it is the fastest known encoder.  But notcurses is working hard to beat it, so who knows where the outcome will be. :)
