### ISSUE TITLE
More beginner friendly example

### ISSUE THREAD

**Issue by favetelinguis** [fdehau/tui-rs#145]
I wanted to give this a try and just copy pasted the example into my editor and trying to run cargo run. However im getting the following errors. I find the documentation lacking for this. What else do I need to add to get it working?
```rust
use std::io;
use termion::raw::IntoRawMode; failed to resolve: use of undeclared type or module `termion`    use of undeclared type or module `termion`
use tui::backend::TermionBackend;
use tui::Terminal;

  fn main() -> Result<(), io::Error> {
     let stdout = io::stdout().into_raw_mode()?; no method named `into_raw_mode` found for type `std::io::Stdout` in the current scope    help: items from traits can only be used if the trait is
     let backend = TermionBackend::new(stdout)?; the `?` operator can only be applied to values that implement `std::ops::Try`    the `?` operator cannot be applied to type `tui::backend::termion
      let mut terminal = Terminal::new(backend)?;
      Ok(())
  }
```

This is mt Cargo.toml

```
[package]
name = "bfg-app"
version = "0.1.0"
authors = ["user"]
edition = "2018"

[dependencies]
tui = "0.5.0"
```

**Comment by fdehau** [comment]
As suggested by the error message, the compiler does not know about "termion". Adding
```toml
termion = "1.5"
```
to your dependencies should fix the issue. This is because `tui` is build on top of optional backends and in your particular case `termion` is required in order to build the `TermionBackend`. I think I made it clearer in 4436110c44da0d222be9c60d2da9ec5d261b8558.
