### ISSUE TITLE
Divide by zero (sparkline)

### ISSUE THREAD

**Issue by bombela** [fdehau/tui-rs#146]
https://github.com/fdehau/tui-rs/blob/4436110c44da0d222be9c60d2da9ec5d261b8558/src/widgets/sparkline.rs#L92

This can fail if max == 0. Which will happen if either max is explicitly set to 0, or calculated from a dataset full of zeros.

I think the solution is to simply print nothing in this case, since, well... there is obviously nothing to be seen.

Will be happy to send a PR but wanted advice first.

**Comment by fdehau** [comment]
Thanks for pointing that out and sorry for the late response on this. Printing nothing would not have worked in all cases since a diff with the previous buffer needs to be computed. Setting the values to zero in this case let the terminal knows that an empty character should be emitted in place of the previous ones if any.
