### ISSUE TITLE
Add `a + ?sized` to trait bounds on `terminal::Frame.render` to allow for dynamic dispatch

### ISSUE THREAD

**Issue by Thermatix** [fdehau/tui-rs#178]
So My plan is to create and store widgets in a tree structure then recursively walk the tree to draw each widget. This is because I want to be able to add or remove widgets to the tree during runtime (for example, plugins that want to add a new UI element will fire off a register widget event or add/remove widget event).

To do this I want to put the widget in a box inside of a struct (wrapper with custom functionality and meta information) inside of a tree (you can see this [here][1]), but I can't, rust won't let me because `error: the 'render' method cannot be invoked on a trait object`. 

My understanding of this is because the `render` method of `Trait tui::widgets::Widget` has a `sized` bound on it:

```rust
fn render<B>(&mut self, f: &mut Frame<B>, area: Rect) where
    Self: Sized,
    B: Backend, 
```

Someone suggested:

> since it's generic over W: Widget which would imply Sized
> 
> nice, tbh, you could probably try to open a PR for this thing: https://docs.rs/tui/0.6.1/src/tui/terminal.rs.html#47
> adding a + ?Sized bound on that line seems like it should work
> and would make dynamic dispatch scenarios like yours easier

thing is, I don't quite understand what they meant by `a + ?Sized` but I thought you might as the crate owner (I'm still fairly new to rust so I'm still quite ignorant on things like this).

EDIT:
I think this is what he was on about? 
```rust
    pub fn render<W>(&mut self, widget: &mut W, area: Rect)
    where
        W: Widget + ?Sized
    {
        widget.draw(area, self.terminal.current_buffer_mut());
    }
```

Still didn't fix the issue  in the render method in the following code:

```rust
pub struct WidgetMeta {
    ui: Box<dyn widgets::Widget>,
    size: u16,
    colourId: String,
    children: Option<ElementManager>,
}

impl WidgetMeta {
    pub fn render(&self, mut frame: &mut F<B>, constraint: &layout::Rect) {
        frame.render(&mut *self.ui , constraint.clone()); // the size for values of type `(dyn tui::widgets::Widget + 'static)` cannot be known at compilation time  doesn't have a size known at compile-time  help: the trait `std::marker::Sized` is not implemented for `(dyn tui::widgets::Widget + 'static)`

    } 
}
```

[1]: https://github.com/Thermatix/boo/blob/871125a2ab8f089c81c21da9dfa7b39ef0cfdcb8/src/interface.rs

**Comment by fdehau** [comment]
I'm not sure to have understood your objective but some things let me think this is either not the best approach or not the appropriate crate for your project. `tui`'s widgets have been designed to be consumables objects with the sole purpose of being some high-levels drawing tools. They don't hold state (at least for now) and two calls to `render` might not return the same output (if for example an internal iterator is consumed). In brief they are not meant to be stored since this crate take an "immediate" approach when it comes to rendering and widgets don't take ownership of the data they draw (at least when it is possible).

For an alternative that already rely on a tree of widgets, have you looked at https://github.com/gyscos/cursive and this nice [comparison](https://github.com/gyscos/cursive/wiki/Cursive-vs-tui%E2%80%90rs) of the two crates ?
