### ISSUE TITLE
Inactivity TUI

### ISSUE THREAD

**Issue by TimonPost** [fdehau/tui-rs#192]
Good day, 

I talked to some people and saw some comments about the inactivity of TUI. There are some problems that people see:

1. No release in 3 months
2. Pull requests remain open for a long time
3. Issues remain open for a long time
4. Dependencies are lagging behind

It would be a waste if a cool crate such as TUI were to go into thin air. That's why I and others wonder how much motivation, time, sense there is left of you to finish this library. I don't know what the reason for the inactivity is, but I know that there are always people who might want to help reduce the work pressure. There are a number of ways that that can happen:

1. Create a GitHub organization and add trusted maintainers so this library can grow further without the need for you to put in more work.
2.  A fork can be made and development can move on from there, but that wouldn't be the best idea because there would be two libraries doing the same thing.
3. Ask if the CLI workgroup would like to take over work or manage this crate. 
4. Ask on Reddit if there are volunteers that want to help. 
5. Invest some more time yourself. 

I would like to hear your reaction on this, and on how we can bring some life back into this library. You've done a great job so far, let's keep it up!

**Comment by fdehau** [comment]
Hi. Finding a good balance between my personal life, a demanding full-time job and open-source projects is a difficult thing to do. It's true that I have not been able to dedicate much time to this project in recent months. The fact I had never thought this project would get that much attention and that it is part of an ecosystem I don't have the chance to use in my day-to-day job does not help either.

I will try to resume a more active presence because I'm still interested in the project and its future. You reaching out and the community showing its interest is also a big motivation to invest back some time. I'm also all for bringing more direct contributors to the project. I don't know if a GitHub organization is needed for that or how the vetting process would go but I would encourage all people interested in an active role in this project to manifest themselves.

**Comment by Canop** [comment]
Take care, we understand very well as it's a very shared problem.

If you'd like to discuss tui-rs contributions, or rust, or programming, there are a few open chats, like for example

- the crossterm discord channel (Timon is Crossterm's leader): https://discordapp.com/channels/560857607196377088/560857607196377090
- la salle miaou "code & croissants", une salle café pour codeurs et sympathisants (que je gère): https://miaou.dystroy.org/3
