### ISSUE TITLE
Missing widgets from blessed-contrib

### ISSUE THREAD

**Issue by orhanbalci** [fdehau/tui-rs#2]
Hi @fdehau 
Are you planning to add missing widgets from blessed-contrib like stacked-gauge donut etc. 
It  would also be nice to have some more shapes like triangles to draw on canvas widget.

**Comment by fdehau** [comment]
Hi @orhanbalci.
Sorry for the late response. The plan for this crate was not primarily to include all widgets from blessed-contrib and termui. However, if you consider that something is missing or that it would be useful for a fair amount of users, i would happily accept any contributions. On the other hand, both widgets and shapes support custom implementations so that you might be able to design your owns (event if the current documentation is not very clear about that).
