### ISSUE TITLE
mouse left click pauses program

### ISSUE THREAD

**Issue by nree** [fdehau/tui-rs#207]
crossterm backend on Windows 10, mainly using the example crossterm demo with modifications as I'm learning / trying out widgets.

A left mouse click will pause the program. Can see it happen with a gauge widget.
Most other inputs will resume the program (like a right mouse click or just about any key input). Left mouse click doesn't resume. But it'll re-pause everytime.

Happens in command prompt & powershell.
But doesn't happen in terminal emulators like Microsoft Windows Terminal or Cmder.

Do you know what's causing it?

**Comment by fdehau** [comment]
Sorry for the late response, I've no idea what could trigger the issue unfortunately. If you still have the issue could you fill out an extensive bug report, see template [here](https://github.com/fdehau/tui-rs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by WildStriker** [comment]
Hey, I stumbled across this and I believe this issue is not an issue but a feature.

It sounds like "Quick Edit" mode is enabled which when you first click start the command prompts \ power shell enters text selection mode.  In this mode apps are frozen until text selection is canceled or copied (esc \ right click)

I played around with this, and looked into how crossterm was handling things... And there is a few options to turn it off:

1. Easiest one (No Code) You need to manually turn it off.  Right click the title bar and going to properties and unchecking "Quick Edit Mode" (need to reload window for effects to take or do this after starting the application)
![image](https://user-images.githubusercontent.com/19638916/82384364-59bfca00-99f5-11ea-982e-174b973dc371.png)

2. Second Easiest and one that applies to @nree scenario, If you wish to have your application deal with this and turn on Mouse Events change the `execute!` macro code:
```rust
    // execute!(stdout, EnterAlternateScreen)?;
    execute!(stdout, EnterAlternateScreen, event::EnableMouseCapture)?;
```

- and add this in the "quit" \ "q pressed" event for clean up:
```rust
            Event::Input(event) => match event.code {
                KeyCode::Char('q') => {
                    disable_raw_mode()?;
                    // execute!(terminal.backend_mut(), LeaveAlternateScreen)?;
                    execute!(terminal.backend_mut(), LeaveAlternateScreen, event::DisableMouseCapture)?;
                    terminal.show_cursor()?;
                    break;
                }
```
3. This is the one I did at first before realizing the MouseCapture Events took care of it for you. 😅  It may be useful if you want to turn this off but not have mouse capture events enabled so sharing this solution... Probably could be written better somehow.

- First need need a few additions to the `cargo.toml` file:
```toml
# --snip--
[dependencies]
# --snip--
crossterm_winapi = { version = "0.6.1", optional = true }
winapi = { version = "0.3.8", optional = true }
# --snip--
[[example]]
name = "crossterm_demo"
path = "examples/crossterm_demo.rs"
required-features = ["crossterm", "crossterm_winapi", "winapi"]
```
- `crossterm_winapi` is an abstraction over winapi that makes it a bit easier to use.

- Now you can add code to turn off Quick Edit:
```rust
use crossterm_winapi::{ConsoleMode, Handle};
use winapi::{shared::minwindef::DWORD, um::wincon::ENABLE_EXTENDED_FLAGS};
// --snip--
fn main() -> Result<(), Box<dyn Error>> {
    let cli: Cli = argh::from_env();

    // windows requires some additional configuring to disable Quick Edit
    let console_mode = ConsoleMode::from(Handle::input_handle()?);
    let mut dw_mode = None;
    if cfg!(target_os = "windows") {
        // Not passing these will disable these extended flags
        // ENABLE_INSERT_MODE | ENABLE_QUICK_EDIT_MODE
        // https://docs.microsoft.com/en-us/windows/console/setconsolemode
        const DISABLE_FLAGS: DWORD = ENABLE_EXTENDED_FLAGS;

        dw_mode = Some(console_mode.mode()?);

        console_mode.set_mode(DISABLE_FLAGS)?;
    }
    // --snip--
}
```
- and in the quit event:
```rust
            Event::Input(event) => match event.code {
                KeyCode::Char('q') => {
                    disable_raw_mode()?;
                     if let Some(dw_mode) = dw_mode {
                         console_mode.set_mode(dw_mode)?;
                     }
                     execute!(terminal.backend_mut(), LeaveAlternateScreen)?;
                    terminal.show_cursor()?;
                    break;
                }
```

Hope this helps, if anything an issue should be opened at crossterm if others find it helpful to have some API to turn off Quick edit mode outside the use of Mouse Events.
...But I think that was the intention of extracting out crossterm_winapi in the first place though, to allow direct access to the winapi

**Comment by fdehau** [comment]
Thanks for this very detailed report. The observed behavior now makes a lot more sense. The second solution seems the most approachable and it would make the crossterm demo on par with the termion one. I've made the change in #308.
