### ISSUE TITLE
Text Style Background should affect whole Row/Cell in List and Table

### ISSUE THREAD

**Issue by Ynscription** [fdehau/tui-rs#239]
When using Text::styled in a List or Table, the background color only affects the text. I believe it should affect the whole Row/Cell in which the text is in.

**To Reproduce**
```
let splits_list = splits.iter().map(|(txt)| {
    Text::styled(Cow::from(txt), 
        Style::default()
            .bg(Color::Red))
});
let mut splits_list = List::new(splits_list)
    .style(normal_style1);
f.render(&mut splits_list, chunks[0]);
``` 

**Screenshots**

![Tui List BG](https://user-images.githubusercontent.com/6177465/76576577-c2a13800-64c2-11ea-96ec-ac654266d995.png)

**Desktop:**
 - OS: Tested on [Linux Mint Cinnamon and Windows 10]
 - Terminal Emulator [Gnome Terminal, Power Shell and Cmd]
 - Font [Monospace and Consolas]
 - Crate version [0.8]
 - Backend [crossterm]

**Comment by fdehau** [comment]
I'm not sure how I feel about this. While I see why one could expect this behavior, the proposed change is kind of implicit. What do you think if instead we introduced a wrapping `Item` struct where this styling can be applied ? Something like:

```rust
struct Item<'a> {
    content: Text<'a>,
    style: Style
}
```
where in your case:
```rust
let item = Item {
    content: Text::styled(txt, Style::default().fg(Color::Green)),
    style: Style::default().bg(Color::Green)
};
```

**Comment by Ynscription** [comment]
That sounds like a great solution to keep the previous functionality and add the expected behaviour I described.

**Comment by Extrawurst** [comment]
Having the same issue! It would be great to have a solution to it.

BTW. this project is awesome! :)

**Comment by pebbleKite** [comment]
@fdehau @Ynscription 
1. What would you say the best interaction of `struct Item` with `selected`? Should the selected styling affect the wrapping layer or the content only?
2. In the table case, should the wrapping style of `Item` be applied to the entire row, or each cell be an instance of `Item` (instead of the current `D where D: Display`)

**Comment by fdehau** [comment]
@pblkt 
1. I think it's reasonable to expect that a user would be able to customize the style of both the `Item` and its content when it is selected. This may imply a breaking change in the way we expose this setting.
2. It's a bit early to apply the same logic to table but given that the table is currently row oriented it would make sense to have a more complex `Row` struct instead of a introducing an `Item`.

**Comment by teohhanhui** [comment]
And allow text alignment too... :see_no_evil:

**Comment by pblkt** [comment]
@fdehau 
What are your thoughts on a unified interface for both table(`Iterator<Iterator<TextCell>>`) and list(`Iterator<TextCell>`)?

 Something like
```rust
pub struct TextCell<'b> {
    data: Cow<'b, str>,
    style: Option<Style>,
    fill_color: Option<Color>,
    alignment: TextAlignment,
}
impl<'b> TextCell<'b> {
    // ...snip...
    pub fn set_in_buf<S>(&self, buf: &mut Buffer, x: u16, y: u16, string: S, width: usize) -> 
    where
        S: AsRef<str>,
    {
      // implement using set_stringn and grapheme count
    }
    // ...snip...
}
```
 Other having one interface this has tackles alignment (#174) as well as styling a single cell in a table

**Comment by teohhanhui** [comment]
I think a `Table` should definitely have a `Row` struct. Just having cell-level control is not enough.

**Comment by pblkt** [comment]
Is there a way to set the margin on the row or anywhere in the table?
As far as my understanding goes it's not anything in the exposed API

**Comment by pblkt** [comment]
@teohhanhui I did, and now re-read it - still don't quite know what margins you mean.

I'm probably missing something, but  [#299(comment)](https://github.com/fdehau/tui-rs/issues/299#issuecomment-638458691) does not have any special margins for any row/cell, but rather the global margins of the table.

Can you explicitly say what margins should be available in your view please?

**Comment by teohhanhui** [comment]
You're right, there's not yet a proposal for margins at the row / cell / etc. levels. But I'm thinking ahead since this proposal is about allowing greater customizability at the sub-widget level, right? Anyway, I can illustrate the same point with background colors...

The thing to note from https://github.com/fdehau/tui-rs/issues/299#issuecomment-638458691 (and the comments that follow) is that the selector is treated as part of the row, not part of the table, also not part of the cell. So if we don't have a `Row` struct, there would not be a good way to say: "colour each row with alternating white / grey backgrounds, but colour the first cell with light blue background".

**Comment by pblkt** [comment]
You're talking about something like
```rust
struct Row{
    selectorCell: todo!(), // some selector styling options
    horizontalMargin: Margin,
    content: Iterator<TextCell>
}
```
?

Additionaly, I think the `selector` as an object can be avoided if the selection is affected as a closure 
```rust
Fn< Iterator<TextCell> -> Iterator<Textcell> >
```
and let the user define a selector if they choose. 

What we're sketching here is already complex. I think it's worth either trimming existing struct fields from what exists or a decision that certain features will never exist in this API. Otherwise there's a risk in something that's more complex to learn the surface on then reimplement.

**Comment by Ma27** [comment]
@fdehau while this seems to fix the background of all list-items, a full line isn't colored when using e.g. `.highlight_style_diff(StyleDiff::default().fg(Color::Green)`.
