### ISSUE TITLE
Branch confusion

### ISSUE THREAD

**Issue by bemeurer** [fdehau/tui-rs#26]
Today I was trying to use tui and so I went to try and walk through the examples. To my surprise I couldn't get them to work because `MouseBackend` didn't seem to be a thing. After some investigation I figured this was due to the fact that `master` was tracking development, and I had to go to the last release tag (`0.1.3`) to find the compatible examples.

It might be more reasonable to create a `devel` branch, and only merge changes to `master` when the update is released. This way anyone coming to the GitHub repository immediately finds the correct source and examples.

**Comment by fdehau** [comment]
Thanks for pointing that out. After giving it some thoughts, I've chosen to keep the master branch as the development branch given the size of the project.

However, in order to avoid any confusion for newcomers, I've moved the documentation inside the code. From now on, the rendered documentation, as shown on https://docs.rs/tui, should always match the latest release.
