### ISSUE TITLE
draw vs. render

### ISSUE THREAD

**Issue by ratijas** [fdehau/tui-rs#27]
`Group` layout is confusing.  It has method `render` like an ordinary widget, but it lacks a counterpart method `draw`.

I tried to separate drawing logic from main App's single method and split it up into widgets, and call `render` on them. For widgets i have to implement the `draw` method — the only one required by the trait. But no way! I can't, not without the reference to a terminal, which is needed for `Group::render`.

```rust
impl Widget for MainViewController {
    fn draw(&self, area: &Rect, buf: &mut Buffer) {
        Group::default()
            .direction(Direction::Vertical)
            .sizes(&[Size::Min(0), Size::Fixed(3)])
            .render( ??? );
    }
}
```

I can see `Group::render` accessing terminal's layout cache, but it doesn't make me feel any better. Any ideas?

**Comment by fdehau** [comment]
I agree that `Group` might be confusing given its method name. The reference to `Terminal` is, as you understood it, used to cache the layout since its computation may require significant time in the process of drawing complex applications. However, I have never thought of it as a `Widget` which has no knowledge of the layout and it should be considered as a tool to help you with the layout management only. It might not be the best solution in terms of ergonomics though and I'm open for new ideas on this particular subject :).

Given the current state of the library, you might as well do the distinction between "custom widgets" that implements the `Widget` trait and are self contained and "containers" that may call `Group` and interacts with the terminal in some way.

**Comment by ratijas** [comment]
Glad you are online.

Well, library itself is cool, except for the `render` part. I've tried to build input handling layer on top of it and `termion` backend, and it's going fine so far, but it needs `Group::draw` for nested views. One possible hack would be to make terminal a global variable (with `lazy_static` or whatever) — not too bad, since we rarely need more than one of them during application's lifetime.

My second point is, suppose than I'm sure there would be at most 5 groups at screen; then can I damn neglect the layout computation time, because something's telling me that rendering graphics would take about few orders longer anyway? It's like "The only speed I care is the speed of my job getting done" — being on slippery ground, I admit.

Lastly, the layout cache itself can be turned into a global, instead of a terminal. Or pre-generate them like `condor` does (I'm not familiar with `condor` or its internals though):

```
// Generate the widget identifiers.
widget_ids!(struct Ids { canvas, counter });

// A unique identifier for each widget.
let ids = Ids::new(ui.widget_id_generator());
...
widget::Text::new(DEMO_TEXT)
    ...
    .set(ids.counter, ui);
```

**Comment by fdehau** [comment]
Regarding your first point I don't like the idea of making the terminal a global object itself. If you want to remove the link between the Group object and the terminal then you can surely create a global cache for the layout computation (lazy_static and stuff). Although, the next issue is how do you expose this to the user and when and what entries would be cleaned. I've decided to hide this from the user for now, thus the link to the terminal.

The second point is more difficult to discuss since i don't have a lot of data to explain my choice. At the time of first writing the lib, it appeared to me when profiling a sample app that the layout computation could take a significant time compared to the time required to draw the complete UI. This might be based on a layout lib itself, an invalid usage on my part or something else. If a change would have to be made and that caching the layout is proven to be not useful regarding performance, I'm totally OK to remove it. But i would rather get it right this time and base this choice on actual data.

Finally, `conrod` has a lot of nice ideas and was definitely a project i took inspiration from when I started to work on this library. But while it is certainly superior in terms of features this comes at the cost of complexity. The last time I've check they were maintaining a DAG of widgets using those ids you mentioned and tried to expose [an immediate API implemented as a retained one](http://docs.piston.rs/conrod/conrod/guide/chapter_1/index.html#is-conrod-immediate-or-retained).

**Comment by ratijas** [comment]
Well, I ended up writing most of the messanger's interface in one method, separating only those widgets which do not require layout calculation or perform it manually.  Now it is open-sourced, however lacks the README and documentation (report for university doesn't count). Can be found by link bellow. Can be used as `tui`'s demo or whatever.

![screenshot_20171121_132822](https://user-images.githubusercontent.com/6737986/33118021-8e07eb36-cf7b-11e7-97eb-bbabb7a08951.png)
[ratijas/mess-client](https://github.com/ratijas/mess-client/blob/master/src/app.rs#L178)

Anyway, thanks for the lib. I've enjoyed using it, and hope to get back soon!
