### ISSUE TITLE
Request: mark methods as deprecated before removing them

### ISSUE THREAD

**Issue by DarrienG** [fdehau/tui-rs#275]
**Is your feature request related to a problem? Please describe.**
I know this is technically pre-1.0, and I understand it takes a little more work to do and a bit more planning, but it would be super nice if methods were marked as deprecated before fully removed, even if it were only in point versions. 

Going from 0.6.0 -> 0.7.0 brought incompatible changes
Going from 0.8.0 -> 0.9.0 brought incompatible changes

(both for pretty standard methods)

SemVer says breaking changes should be major updates X.Y.Z (where breaking is X).

I understand if you don't want to, or are waiting for 1.0, but as a user, it's a little frustrating.

Library is superb otherwise.

**Describe the solution you'd like**

[Mark methods as deprecated](https://github.com/rust-lang/rfcs/blob/master/text/1270-deprecation.md#intended-use) before removing them and potentially moving breaking api changes to major version updates.

**Describe alternatives you've considered**
Fixing issues as they come in.

**Additional context**
No other context. I appreciate all of the work done on the library. It is fantastic.

**Comment by Minoru** [comment]
> SemVer says breaking changes should be major updates X.Y.Z (where breaking is X).

It only says that for x>0. When x=0, [a different rule applies](https://semver.org/#spec-item-4): "Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable."

**Comment by DarrienG** [comment]
I'm aware SemVer pre-zero has different rules, but so many crates are labeled as major version 0, so I figured the same rules might apply.

I did include this:

> I understand if you don't want to, or are waiting for 1.0, but as a user, it's a little frustrating.

to specify.

**Comment by fdehau** [comment]
Thanks for providing this feedback. I'm perfectly aware that the situation is not ideal for users of the crate so let me explain why I have been pushing breaking changes like this.

First of all, this is due to the lack of time I can dedicate to the work on this crate. Deprecating feature, introducing a replacement and finally removing them would require me to invest more time than I actually have.

Secondly, as @Minoru highlighted and as you acknowledged, this is still accepted by the community until the crate reaches 1.0.

Finally, although this crate has existed for more than three years now, it has only started getting attention in the last eight months or so. This is incredible opportunity for feedback and has highlighted a lot of rough edges that need to be fixed so that people can use it to its full potential.

Hopefully, I don't expect as many breaking changes in the next releases and I will try to be a bit more careful in how those changes can impact end users =).

**Comment by DarrienG** [comment]
I totally understand! I'm sure you don't get paid to work on this either :sweat_smile: 

I've extensively used this crate for about a year so I totally expect to see some teething pains along the way especially for a 0 ver crate. I just wasn't sure if it was actually following 0 for semver, or if it was following [0ver](https://0ver.org/) like a lot of rust crates.

Whatever it takes to get us to 1.0! I appreciate all of the work done on the crate. Thanks so much for all of the time put into it :)
