### ISSUE TITLE
Request: Example using Crossterm's EventStream

### ISSUE THREAD

**Issue by sum-elier** [fdehau/tui-rs#279]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use tui-rs api with async capabilities in mind. For that I am planning to use Crossterm's `EventStream` and async functions.

**Describe the solution you'd like**
A modified version of `crossterm_demo.rs` which uses `EventStream` and async functionality using either Tokio or async-std runtimes.

**Describe alternatives you've considered**
Using the library as it is explained in the existing `crossterm_demo.rs` without async and `EventStream`
Trying to implement the requested async demo myself but without success.

**Additional context**
No additional context.

**Comment by fdehau** [comment]
I think this is a bit out of the scope of the crate. Some people already reporting that the examples are a bit too complex so I don't think it is a good idea to add the async layer on top of that. Furthermore, since the input events are not directly managed by the crate, I would advocate that this kind of input handling be demonstrated (if not done already) in the crossterm repo.
