### ISSUE TITLE
how to change/render buffer after draw

### ISSUE THREAD

**Issue by extrawurst** [fdehau/tui-rs#281]
**Is your feature request related to a problem? Please describe.**
I want to change a just a *portion* of the screen after a `terminal.draw`.

**Describe the solution you'd like**
How can I use the tui tools to render widgets into the current screen buffer?

**Describe alternatives you've considered**
```
terminal.current_buffer_mut().set_string(
                0,
                0,
                "/",
                Style::default(),
            );
```

```
terminal
                .get_frame()
                .render_widget(...);
```

```
terminal.backend_mut().set_cursor(0, 0)?;
terminal.backend_mut().write("a".as_bytes())?;
```

all of the above will not appear on the current buffer. it takes for them to appear only in the next `draw`

**Comment by fdehau** [comment]
Reading your issue, the first question is could you provide a bit more details on why you need to change a portion of the screen outside of `terminal.draw` call ?

Then to answer your question, the changes to the current buffer are only appearing on the next draw call because you haven't flushed its content to the terminal. You may want to use `terminal.flush` (this is in fact the last step of the `terminal.draw` function) to do so. 

Why is that ? Because `tui` buffers all the output to only emit the necessary ansi escapes commands required to reflect the changes between two draw calls.
