### ISSUE TITLE
blessed supports mouse click, drag and scroll since 5 years ago

### ISSUE THREAD

**Issue by sebolio** [fdehau/tui-rs#303]
Hi, I really like tui-rs and I see it's used in many projects, but it's 2020 and even Windows console supports mouse events (tested with [Micro Editor](https://micro-editor.github.io) which supports drag and scroll), why doesn't tui-rs?

**Comment by extrawurst** [comment]
Probably because no one with the resources (time and skill) needed it enough to add it. As an open source maintainer myself I can tell you aswell that this sort of rethoric isn't going to get you what you wanted.

**Comment by fdehau** [comment]
Thanks @extrawurst for the polite response :). @sebolio I will assume in good faith that the somewhat rudeness of your question was not intentional. FYI, mouse events are already supported by most backends of tui but they are not well integrated in the library that's all. See my comments in #166 for a bit more context on that.
