### ISSUE TITLE
Incorrect title text

### ISSUE THREAD

**Issue by dave12311** [fdehau/tui-rs#324]
**Describe the bug**
The example block with title code displays the title text incorrectly. It seems like the space characters do not overwrite text previously on screen, so the title text gets overlaid on the command starting the program.

**To Reproduce**
```
[dependencies]
crossterm = "0.17.5"
tui = { version = "0.9.5", default-features = false, features = ['crossterm'] }
```
```
use std::io;
use tui::Terminal;
use tui::backend::CrosstermBackend;
use tui::widgets::{Widget, Block, Borders};
use tui::layout::{Layout, Constraint, Direction};

fn main() -> Result<(), io::Error> {
    let stdout = io::stdout();
    let backend = CrosstermBackend::new(stdout);
    let mut terminal = Terminal::new(backend)?;
    terminal.draw(|mut f| {
        let size = f.size();
        let block = Block::default()
            .title("Test Title")
            .borders(Borders::ALL);
        f.render_widget(block, size);
    })
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/17969647/84764158-928b9880-afcd-11ea-83a3-19ca5c5130f4.png)

If I `terminal.clear()` before `terminal.draw()`, it works.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Terminal Emulator: Xfce4-terminal
 - Font: MesloLGS NF
 - Crate version: 0.9.5
 - Backend: crossterm

**Comment by fdehau** [comment]
If you are not clearing the screen nor using an alternate screen, this is the expected behavior. What are you trying to achieve here ?

**Comment by dave12311** [comment]
I think it would be more useful if the `.title()` function would overwrite the whole title space instead of only the non-whitespace characters.

**Comment by fdehau** [comment]
This would go against how the crate works internally. At each frame it computes the minimum diff to apply to the previous frame to get the expected output while minimizing the number of ansi escapes sequences generated (inspired by how a "damage buffer" would work). The crate assumes the space it draws to is blank on the first render so you need to make sure it is the case by either writing to a blank part of the terminal, clearing the screen or using an alternate screen.

This has not been a problem for most users of the crate, so you may have a different use case than everybody, that's why I wanted more details on what you wanted to achieve.
