### ISSUE TITLE
Enable use of Termion's AlternateScreen

### ISSUE THREAD

**Issue by Nhanderu** [fdehau/tui-rs#33]
Hi there,

I was wondering if I could use [Termion's AlternateScreen][1] with tui-rs and I found myself adding the following to your code:

```rust
pub type AlternateScreenBackend =
    TermionBackend<termion::screen::AlternateScreen<termion::raw::RawTerminal<io::Stdout>>>;

impl AlternateScreenBackend {
    pub fn new() -> Result<AlternateScreenBackend, io::Error> {
        let raw = io::stdout().into_raw_mode()?;
        let screen = termion::screen::AlternateScreen::from(raw);
        Ok(TermionBackend { stdout: screen })
    }
}
```

It worked just as I expected! But then, I faced another problem: I couldn't use `print!` or even write to `stdout`, I needed to write to `backend.stdout`, but that would require some changes in the lib's API, since it's a private attribute.

Exposing it doesn't seem like a good solution for me. We could implement `std::io::Write` for `Terminal` and just call `self.backend.stdout.write` internally.

What do you think about that? Is the change pertinent? Do you have another solution? I'm still in the "fighting the borrow-checker" phase, but I would love to help with that or any other feature.

Also, thanks for the great lib! :)

[1]: https://docs.rs/termion/1.5.1/termion/screen/struct.AlternateScreen.html

**Comment by Nhanderu** [comment]
Another thing: any reason for you to choose `backend.flush` to return `Result<(), io::Error>` instead of `io::Result<()>`?

**Comment by fdehau** [comment]
Sorry for the late  just opened a PR with the functionality you were missing.

**Comment by fdehau** [comment]
Sorry for the late response

I've just opened a PR with the feature you were missing. However, implementing `std::io::Write` for the `Terminal` would be difficult to my knowledge because of the `RustboxBackend`. Therefore, i've only added the write implementation for the `TermionBackend` so that you could do something like `terminal.backend_mut().write(...)` when you use `termion`.

Also thanks for the tip about those `Result`, I've updated them too =).

Let me know if you are fine with this solution.

**Comment by Nhanderu** [comment]
Hey!

Well, everything seems to be working fine. Thanks for putting your effort on this!

I just did a really small fix in the code, just to make `AlternateScreenBackend` public (#37).

Again, thanks! 🤗
