### ISSUE TITLE
docs example links are broken

### ISSUE THREAD

**Issue by johnalupton** [fdehau/tui-rs#370]
**Describe the bug**
links from the docs to examples are broken 

**To Reproduce**
go to this page [https://docs.rs/crate/tui/0.10.0](https://docs.rs/crate/tui/0.10.0)
and the links to the examples, e.g. 
[https://docs.rs/crate/tui/examples/block.rs](https://docs.rs/crate/tui/examples/block.rs)
are broken

**Expected behavior**
taken to a page with the docs

**Screenshots**

**Desktop (please complete the following information):**
Chrome browser

**Additional context**
correct path is 
[https://docs.rs/crate/tui/0.10.0/source/examples/block.rs](https://docs.rs/crate/tui/0.10.0/source/examples/block.rs)

**Comment by fdehau** [comment]
I see the issue but also I'm a bit unsure what's the best way to fix it. The problem is that those links are relative links supported natively by Github (see: https://github.blog/2013-01-31-relative-links-in-markup-files). docs.rs is taking the same README but render it in its own way. I'll try to find a way to have them work nicely on both platforms.

**Comment by BenjaminLiuPenrose** [comment]
Hello, it is really inconvenient that all links in docs.rs are broken. I think for the documentation part, we may learn from how other rust projects do their doc (e.g. [rayon](https://github.com/rayon-rs/rayon/blob/master/README.md), they have consistent github&docs.rs doc link)
