### ISSUE TITLE
Random layout bug

### ISSUE THREAD

**Issue by bestouff** [fdehau/tui-rs#39]
Hi,

I've integrated a simple example from the doc which does nothing but display 2 blocks, and this example randomly displays overlapping boxes. Here's the code excerpt:
```rust
fn draw(t: &mut Terminal<RawBackend>) -> std::result::Result<(), std::io::Error> {                                                                             
    let size = t.size()?;
                                                                               
    Group::default()                                                           
        .direction(Direction::Vertical)                                        
        .margin(1)
        .sizes(&[Size::Fixed(10), Size::Max(20), Size::Min(10)])               
        .render(t, &size, |t, chunks| {                                        
            Block::default()
                .title("Block")                                                
                .borders(Borders::ALL)
                .render(t, &chunks[0]);
            Block::default()                                                   
                .title("Block 2")
                .borders(Borders::ALL)
                .render(t, &chunks[2]);                                        
        });

    t.draw()                                                                   
}
```
And here are the results - randomly one or the other (note that I always press `^L` before running the example):
![capture d ecran de 2018-02-22 13-45-49](https://user-images.githubusercontent.com/1163188/36539508-62837882-17d7-11e8-84b0-038bb1b6bf30.png)
![capture d ecran de 2018-02-22 13-45-58](https://user-images.githubusercontent.com/1163188/36539515-65fc0de4-17d7-11e8-933a-3d4340bbb802.png)

**Comment by bestouff** [comment]
FWIW I've tested Gnome-Terminal and tilix (both are VTE-based).

**Comment by bestouff** [comment]
Moreover, if I just replace `chunks[2]` with `chunk[1]` sometimes I see this panic:
```
thread 'main' panicked at 'attempt to add with overflow', /home/xav/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.2.0/src/layout.rs:57:9
```

**Comment by fdehau** [comment]
Thanks for the complete bug report. After some research, the problem is linked to the library used to compute the layout. When i'm getting the results back, the height of the second chunk is either 0 or a negative value which converted back to an unsigned integer leads to an overflow in latter computations (and thus the panic you exhibited). This kind of behavior seems to happen only when min and max constraints are mixed together. I fixed the panic and change the documentation to advertise a more reliable solution for the moment. However, I will certainly need more time to fix the root of the instability.

**Comment by bestouff** [comment]
OK thanks.
