### ISSUE TITLE
question, is there no abstraction for input?

### ISSUE THREAD

**Issue by pm100** [fdehau/tui-rs#391]
I am writing a new backend and as far as I can see there is no abstraction for input. I mean the way a tui app developer waits for terminal events (keys, mouse, resize,...) is different for each backend. Plus the data they get is not the same.

This is very different from output: output is fully abstracted, the coder uses a uniform API regardless.

Am I correct? Did you consider a common input model.?

**Comment by Byron** [comment]
[`crosstermion`](https://lib.rs/crates/crosstermion) might be of interest to you, as it does provide a common input abstraction, with and without async.

**Comment by pm100** [comment]
I wasnt looking for anything fancy, just adding to the Backend trait, a get_event, and a common set of key / mouse / misc event definitions. Having just ported a TUI app from termion to crossterm it was a pain to have to redo all the input handling

**Comment by fdehau** [comment]
@pm100 I've never found the time to actually implement it and the last time I checked there was no easy way to propose an common interface that would cover all backends. The problem is that this crate tries to not make any assumption when and how it will be called and there are a lot of ways to handle and expose the input events (explicit polls, background thread + channel, async). A contribution would be more than welcome but I would be interest first in an api draft and an rough overview of how you would tackle the issue.

**Comment by pm100** [comment]
ok, I will ponder on it while I build my new backend
