### ISSUE TITLE
cannot get mouse selection working on examples on latest macOS

### ISSUE THREAD

**Issue by yatesco** [fdehau/tui-rs#410]
**Describe the bug**
Neither `cargo run --example list` nor `cargo run --example list --features crossterm` allow mouse selection running the latest `master` branch on macOS.

**To Reproduce**
1. Clone the repository
2. `cargo run --example list`
3. Try and select something with the mouse

**Expected behavior**
Selection should be visible allowing copying to the clipboard

**Desktop (please complete the following information):**
 - OS: macOS
 - Terminal Emulator: Terminal
 - Font: SF Mono Powerline Regular 11pt 
 - Crate version [e.g. 0.7]:"* 25ff2e5 (HEAD -> master, origin/master, origin/HEAD) upgrade crossterm to v0.18"
 - Backend [e.g termion, crossterm]: tried with both termini and crossterm

**Additional context**
The examples include initialising the mouse capture so AIUI mouse selection should work.

**Comment by fdehau** [comment]
If you look at the initialization of the list example, you see that we [enable the capture of mouse events](https://github.com/fdehau/tui-rs/blob/25ff2e5e61f8902101e485743992db2412f77aad/examples/list.rs#L94). My understanding is that this will make your application the only recipient of mouse events and the select feature provided by your terminal emulator no longer work because it does not have access to those events anymore. If you don't care about mouse events you can probably remove this option and the select feature will work again. Otherwise, I'm not familiar with all this ANSI escape magic (they are abstracted away by the different backends), so you would probably get more help from the maintainers of your backend of choice :).
