### ISSUE TITLE
Color::Gray is rendered as Color::White

### ISSUE THREAD

**Issue by DarrenTsung** [fdehau/tui-rs#435]
**Describe the bug**
When you style a `Span` with `.fg(Color::Gray)` or `.bg(Color::Gray)` it renders the `Span` as if `Color::White` was provided. It looks like the code just uses `Color::White`, which was unexpected to me: https://github.com/fdehau/tui-rs/blob/master/src/backend/termion.rs#L156, https://github.com/fdehau/tui-rs/blob/master/src/backend/termion.rs#L182.

**To Reproduce**
Create a paragraph with a styled `Span` with `Color::Gray`, something like:
```
Spans::from(Span::styled(
    "hello world",
    Style::default().fg(Color::Gray),
)),
```

**Expected behavior**
It renders something that is gray.

**Comment by fdehau** [comment]
You missed a section of the bug report template and it would be useful to understand the problem here. Could you report the following values:
    OS: [e.g. Linux,Windows]
    Terminal Emulator [e.g xterm, Konsole, Terminal, iTerm2, ConEmu]
    Font [e.g Inconsolata, Monospace]
    Crate version [e.g. 0.7]
    Backend [e.g termion, crossterm]

In addition, I just added a third tab to the demo that might help us debug your issue: #439. It would be nice if you can run on master:
```
cargo run --example termion_demo
```
navigate to the third tab and add a screenshot of what you are seeing. For example, here's mine:
![Screenshot from 2021-01-01 15-36-04](https://user-images.githubusercontent.com/10096255/103440631-7d174c80-4c47-11eb-970a-da86263c0b57.png)

**Comment by DarrenTsung** [comment]
Gotcha, I omitted it because I thought the bug was as simple as the code incorrectly using `White` instead of `Gray` (when rendering `Gray`), but I see now that it renders `LightWhite` when rendering `White`.

OS: MacOS Catalina 10.15.7
Terminal Emulator: iTerm2 (3.4.3)
Font: Menlo
Crate version: 0.10 (also on latest master)
Backend: termion

Here's what I see on the third tab for the example (for me, gray looks the same as white):
![Screen Shot 2021-01-02 at 10 59 19 AM](https://user-images.githubusercontent.com/1581481/103464614-0717f180-4cea-11eb-8c7c-bcea62f64d91.png)

I believe I'm using the iTerm2 snazzy color scheme: https://github.com/sindresorhus/iterm2-snazzy.
