### ISSUE TITLE
RFC: automatic state management

### ISSUE THREAD

**Issue by fdehau** [fdehau/tui-rs#448]
In `v0.9.0` `StatefulWidget`s were introduced to be able to implement some UI patterns requiring the ability to keep track of internal state between draw calls. In particular, this feature was used to implement a natural scrolling experience in the `List` and `Table` widgets.

The gist of the change was to introduce a `StatefulWidget` trait extending the original `Widget` by providing an additional `State` to the `render` method. This `State` holds the properties the `Widget` needs to remember between two draw calls.

While it worked well enough, this design choice had several drawbacks:
* We have two different traits for widgets.
* It exposes the internal state of the widget to the end-user who has to keep track of it for reasons that may not be obvious to them.
* The trait provides a mutable reference while interior mutability would have been enough (see #311).

Therefore, I propose the following changes to simplify this feature and make it easier to use for end-users:
* Merge `Widget` and `StatefulWidget` in a single `Widget` trait. The new definition looks like this:
```rust
pub trait Widget {
    type State;
    fn render(self, ctx: &mut RenderContext<Self::State>);
}

pub struct RenderContext<'a, S> {
    /// Area where the widget is rendered.
    pub area: Rect,
    /// Buffer where the drawing operations will be temporarly registered.
    pub buffer: &'a mut Buffer,
    /// Internal state associated with the widget.
    pub state: &'a mut S,
}
```
Arguments to `render` are thus replaced by a single `RenderContext` providing access to the previous `area` and `buffer` as well as the new `state` property. The new API is also more resilient of future breaking changes of this kind.
* Keep track of the internal state of a widget by using the [call location](https://doc.rust-lang.org/std/panic/struct.Location.html) (new in Rust 1.46) of `Frame::render_widget` and optionally an additional id provided by the end user. This state is provided automatically to `Widget::render` and is kept around until the widget is no longer referenced in a draw call. The second argument of `Frame::render_widget` becomes `RenderArgs` and a `From<Rect>` implementation is provided to preserve the backward compatibility.

Example migration:

Before:
```rust
use tui::widgets::{List, ListItem, ListState};

#[derive(Default)]
struct App {
  items: Vec<String>,
  list_state: ListState,
}

fn main() {
  let mut terminal = { ... };
  let app = App::default();
  app.list_state.select(1);
  terminal.draw(|f| {
     let items: Vec<ListItem> = app.items.iter().map(ListItem::new).collect();
     let list = List::new(items);
     f.render_stateful_widget(list, f.size(), &mut app.list_state);
  });
}
```
After:
```rust
use tui::widgets::{List, ListItem};

#[derive(Default)]
struct App {
  items: Vec<String>,
  selected: Option<usize>,
}

fn main() {
  let mut terminal = { ... };
  let app = App::default();

  terminal.draw(|f| {
     let items: Vec<ListItem> = app.items.iter().map(ListItem::new).collect();
     let list = List::new(items).select(1);
     f.render_widget(list, f.size());
  });
}
```

This proposed change has been implemented in #443.

**Comment by simast** [comment]
Went through RFC and the PR and have some random thoughts. Let me know if I missed something, but for the auto-tracking state based on call location functionality I assume that these pseudo examples are correct :

```rust
// Works as expected, all lists will get their own state and this state
// is preserved between `terminal.draw()` calls.
f.render_widget(list1, ...);
f.render_widget(list2, ...);
f.render_widget(list3, ...);

// This pattern however requires `.id()` hints on RenderArgs as all lists
// share the same call location.
for list of lists {
  f.render_widget(list, rect.into().id("some unique string per list"));
}

// Am I correct that the following two code snippets below will have different
// runtime behavior with list state?

if something {
  f.render_widget(list, one_rect);
} else {
  f.render_widget(list, another_rect);
}

f.render_widget(list, if something { one_rect } else { another_rect });
```

Also noticed that when creating your own Widgets while reusing other widgets in a composition we will have to make the following changes:

```diff
- block.render(area, buf);
+ block.render(&mut RenderContext {
+   area: ctx.area,
+   buffer: ctx.buffer,
+   state: &mut (),
+});
```

Which is a bit handful, especially that state param.

And one thing that might be an issue with this approach is that for example this scenario:

1. Show a list and allow user to select
2. Hide a list
3. Show the same list again

At step 3 the state is now reset (selection can be preserved but list offset will be always reset). This was not an issue with the old state management however.

**Comment by gin66** [comment]
Pardon me to throw in my 2 cent to this discussion as author of tui-logger.

tui-logger uses an "internal" state. I say "internal". because it is stored in the application data area and tui-logger gets only a reference to it
```
    pub fn state(mut self, state: &TuiWidgetState) -> TuiLoggerTargetWidget<'b> {
        self.state = state.inner.clone();
        self
    }
```

The tui-logger needs internal state for only one reason: The widget builds a one time use/throw away dispatcher queue (while rendering) to which the application is expected to send controlling key events. Then the dispatcher will evaluate those and modify the state automagically without the app designer need to worry about, how tui_logger's interface is.

BTW: The dispatcher queue was just a design choice and perhaps a separate struct with appropriate interface would have been sufficient, but that time I thought it is a great idea.

In the current List-Widget, the additional "state" is just a convenient way to not needing to fiddle around with the ListItems giving them proper styling. But in a nutshell, the "state" is nothing more than data from the application to build the list.

The proposed machinery with using the callback location is extremely sophisticated and perhaps the regular application design will never completely understand it, or will be able to predict side effects, as hinted by simast.

So I propose a much more dumb approach to just define this trait:
```
pub trait WidgetWithState {
    type State;
    fn state(self, state: &mut Self::State);
}
```
or
```
pub trait WidgetWithState {
    type State;
    fn state(self, state: Rc<RefCell<Self::State>>);
}
```

If the Widget wants to be stateful, then just mix in the WidgetWIthState trait. This way the Widget already knows its "state", then the render() does not need the parameter and the annoying ambiguity of render between Widget and StatefulWidget is gone (I have stumbled about this lately).

The nice thing is, that this is an opt-in choice to be WidgetWithState or not. If the Widget designer does not like this and has a better idea to manage state, then he/she is free to do so. Or perhaps the WithWidgetState uses a &mut, but the app designer would love to use a Rc<RefCell<_>>, then it can be done. And vice versa.
