### ISSUE TITLE
Does not build on Windows 10

### ISSUE THREAD

**Issue by Cthutu** [fdehau/tui-rs#492]
## Description
Building tui-rs from the latest code on github does not build.

## To Reproduce
Get the latest code from github (using clone).  Enter `cargo b` to build it.

## Expected behavior
A clean build.

## Screenshots
![image](https://user-images.githubusercontent.com/348614/122198750-56656f00-ce91-11eb-889e-2cad73867d3c.png)

## Environment
- OS: Windows 10
- Terminal Emulator: conemu
- Font: Unknown
- Crate version: 0.15.0
- Backend: N/A

**Comment by fdehau** [comment]
Hey 👋, this is happening because the default backend is `termion` which only works on Unix platforms. A more cross-platform option is to use `crossterm` as explained in [the documentation](https://docs.rs/tui/0.15.0/tui/#adding-tui-as-a-dependency).

I plan to move to `crossterm` as the default backend to provide a nicer experience out of the box on all platforms but I haven't had time to do so yet 😬.
