### ISSUE TITLE
Style can no longer be created as const

### ISSUE THREAD

**Issue by SergeyKasmy** [fdehau/tui-rs#511]
## Description
I was looking for a way to create a const Style at the root of the file, so it would be easier to share styles between different UI elements and so I would only need to change it just in one place to have it apply everywhere. I found this issue #223 and its corresponding PR #226 which shows it has already been implemented in commit 808a5c9. But when I looked into `style.rs` these changes where nowhere to be found. I bisected this change to commit 0ffea49. My questions are: was that intended? Is there any reason for these changed to be removed? I would submit a PR to make them const again but it was probably removed for a reason after all, so I decided to ask about it first. 

## Example
```
const STYLE_NORMAL: Style = Style::new().bg(Color::Gray).fg(Color::White);
const STYLE_HIGHLIGHTED: Style = Style::new().bg(Color::White).fg(Color::Black);
```

**Comment by fdehau** [comment]
I removed the `const` modifier because it was not possible to apply it to all methods of `Style` — `add_modifier` and `remove_modifier` are operating on `bitflags` structs which has no support for `const` as far as I understood. I thought that providing only half the API as const would be more confusing. We can maybe revisit this when `const` support lands in `bitflags`, WDYT ?

**Comment by sigmaSd** [comment]
You can inline the implementations to make them const:

https://github.com/fdehau/tui-rs/compare/master...sigmaSd:const?expand=1

Also I noticed that running `cargo clippy -- -D clippy::missing_const_for_fn` shows that a lot more can be const

**Comment by sigmaSd** [comment]
Actually tests are failing, I'll have to check more

**Comment by sigmaSd** [comment]
Was a typo, fixed now
