### ISSUE TITLE
[0.16] Regression in Constraint::Min for tables

### ISSUE THREAD

**Issue by extrawurst** [fdehau/tui-rs#525]
## Description
Before 0.16 our table layout worked with all columns being precisely sized and then using `Constraint::Min(0)` to use all the rest of available space to fill. This worked and 0.16 did not mentioned anything about this being changes but it does not work anymore.

## To Reproduce
Switching to `Constraint::Percentage(100)` luckily workaround the issue.
See: https://github.com/extrawurst/gitui/pull/845/files

## Expected behavior
The previous behaviour.

## Screenshots
Before we upgraded to `0.16`:

<img width="935" alt="Screenshot 2021-08-15 at 17 12 15" src="https://user-images.githubusercontent.com/776816/129483253-b640e020-2906-45e3-ba79-3c5dcddac979.png">

**After** we upgraded to `0.16`:

<img width="937" alt="Screenshot 2021-08-15 at 17 12 45" src="https://user-images.githubusercontent.com/776816/129483269-2fb7b03b-90bd-4788-bdfd-857f9e6d2806.png">

## Environment
- OS: MacOS
- Terminal Emulator: iterm2
- Crate version: 0.16
- Backend: crossterm

## Additional context
I assume this regression was introduced in: https://github.com/fdehau/tui-rs/pull/514

**Comment by Ninja-Koala** [comment]
I noticed that the table example only shows 2 rows in 0.16 instead of 3 rows which are provided in the code and
which can be seen in the example build with version 0.15 . Is this the same bug or should i report it seperately?

![Screenshot from 2021-11-03 18-29-34](https://user-images.githubusercontent.com/8513665/140160237-290f43e0-5b07-45cd-81cc-e6b0346fc591.png)
![Screenshot from 2021-11-03 18-28-57](https://user-images.githubusercontent.com/8513665/140160265-8d4803e6-967d-473e-b1d4-7754700f02b9.png)
