### ISSUE TITLE
Is there a way to close the popup? 

### ISSUE THREAD

**Issue by veta666** [fdehau/tui-rs#546]
## Description

`Popup` as a widget is very usable. But in current version of `tui-rs` it is not obvious how to close it (if it possible at all).

## Expected behavior

It would be more comfortable, if `popup` could be closed by special button or after some time.

## Screenshots
![image](https://user-images.githubusercontent.com/86791078/137895029-b7529760-cac9-4fe7-a74d-c98f0a6c1196.png)
For example, 
![image](https://user-images.githubusercontent.com/86791078/137895151-79ef0f14-ad1a-4543-bb89-e1b881249b7b.png)

## Environment
OS: Linux,
Backend: termion

**Comment by fdehau** [comment]
Hey 👋 , since `tui` is using an immediate mode API, closing a popup is just a matter of not including the draw call when you build your user interface. I've update the popup example to [show this behaviour](https://github.com/fdehau/tui-rs/blob/c8c03294e101e0005333553964dd15e3530f409a/examples/popup.rs#L95).

**Comment by veta666** [comment]
Thank you very much! And especially for the example!
