### ISSUE TITLE
Is the Documentation for module such as "layout" left empty intentionally?

### ISSUE THREAD

**Issue by rishadbaniya** [fdehau/tui-rs#587]
I got confused on how the constraint method works on ```layout::Layout```. I was expecting some explanation about ```layout::Layout``` struct and its methods. Is the documentation left empty intentionally for developers to figure out themself, or is the library easy to use and it's the problem with me actually for being not so mature in Rust?

**Comment by lbcat06** [comment]
Confuses the hell out of me too, like what is a constraint even doing ? If I don't have one I get index out of bounds error, but I dont know how to use them...

**Comment by rishadbaniya** [comment]
> Confuses the hell out of me too, like what is a constraint even doing ? If I don't have one I get index out of bounds error, but I dont know how to use them...

If you figure out what that constraint does, please fire a PR documenting what it does, i wanna know properly

**Comment by DarrienG** [comment]
Constraint is a way of shaping the size of nodes in a group. For instance, if you have one layout and a number of percentage constraints, you can shape what percentage of the layout each node (say a number of `tui::text::Text`) objects take up.

In my projects, I use it to size nodes (a number of different text objects) to [different sizes](https://gitlab.com/ttyperacer/terminal-typeracer/-/blob/c59e859bf2ca4e404988a5649bf7497832eb2d74/src/info/info_render/styles.rs) and wired up [here](https://gitlab.com/ttyperacer/terminal-typeracer/-/blob/c59e859bf2ca4e404988a5649bf7497832eb2d74/src/info/info_render.rs#L28). Because I can specify constraint, I use different sizes for different screen sizes. So I am able to make resize nodes to take up more or less space. 

Play around with Constraint sizes and watch how the size of your layouts change, it should become more apparent then :)

I use constraints and a number features of tui-rs in my terminal typeracer project which may help: https://gitlab.com/ttyperacer/terminal-typeracer

@TomSchammo if you would like an apt analogy, the layouts used by tui-rs are more similar to the good old Linear Layout: https://developer.android.com/guide/topics/ui/layout/linear Layouts are given an orientation (although size is optional in Android Linear Layout) and placed one after another. Layouts can and should be nested in Linear Layout. Constraint Layout is intended to have all View nodes in one flat layout which like Linear Layout, tui's view system is not intended to do.

**Comment by invokermain** [comment]
I find this so confusing as well, why is it not documented, its non obvious and this library is obvious popular enough (7k stars) to warrant proper documentation no? Am I just too stupid to figure it out?
