### ISSUE TITLE
Be able to have `Block::default().title()` on the bottom of said block.

### ISSUE THREAD

**Issue by Xithrius** [fdehau/tui-rs#625]
## Problem

Context: [`Block::default().title()`](https://docs.rs/tui/latest/tui/widgets/struct.Block.html#method.title)

The title on the top of a block can sometimes be too long, so being able to have it on the bottom of the block would let users have more information per block.

## Solution

I'm not too sure how to program this into the crate, perhaps something like `Block::default().title("An example title").bottom()` would work.

## Alternatives

I don't think vertical titles would be a good idea, so I'm unsure.

## Additional context

An exaggerated example, but other titles cannot be seen (ignore the cut-off time).

![image](https://user-images.githubusercontent.com/15021300/169198943-f727c715-0646-4d87-a490-f3ddf245394f.png)

**Comment by rabirabirara** [comment]
I don't quite understand how moving a title to the bottom of the block would give you more space, since the top and bottom of a block are the same as far as I know.  You might mean, then, having the capability to put multiple titles, one on top and one on bottom.  

Yeah, that might be probably a little overkill to program *into* the library; you could code it yourself using `Layout` and `Clear`, or maybe even just doing away with the border and filling in the symbols yourself.  It would still be time-consuming, though.

Until then https://github.com/fdehau/tui-rs/pull/669; made this for the much simpler functionality of just putting the singular title on the bottom row instead of the top.
