### ISSUE TITLE
Using text characters for color setting is problematic

### ISSUE THREAD

**Issue by nifker** [fdehau/tui-rs#63]
1. A function which allows disabling formatting for the render() would be very useful
2. It is not possible to draw colored text and use '{', '}' or '\' at the same time

**Comment by fdehau** [comment]
I'm working on some breaking changes, the text formatting inside Paragraph is one of them. I'm planning to remove completely the existing markup language since it was really not well thought and rely on the existing `Style` properties. However with the current version, you should be able to use `.raw(true)` on Paragraph to disable the parsing of the markup language.

**Comment by nifker** [comment]
@fdehau Having a reworked system even if it breaks the current would be pretty good :+1:
