### ISSUE TITLE
Rust newb trying to use library

### ISSUE THREAD

**Issue by cjbassi** [fdehau/tui-rs#65]
Hi I'm learning rust and I was wondering if you could help me with an issue I ran into when using this library. (great library btw)

Example code:
```
extern crate tui;

use tui::widgets::Block;
use tui::widgets::Chart;

const TITLE: &str = " CPU Usage ";

pub struct CPU {
    pub chart: Chart<'static, String, String>,
}

impl CPU {
    pub fn new() -> CPU {
        let chart = Chart::default();
        chart.block(Block::default().title(TITLE));
        CPU {
            chart,
        }
    }
}
```

I'm getting an issue due to the `chart.block(Block::default().title(TITLE));` line. The error says
```
error[E0597]: `chart` does not live long enough
  --> src/widgets/cpu.rs:15:9
   |
15 |         chart.block(Block::default().title(TITLE));
   |         ^^^^^ borrowed value does not live long enough
...
19 |     }
   |     - borrowed value only lives until here
   |
   = note: borrowed value must be valid for the static lifetime...
```

but aren't I moving the `chart` value into the CPU struct which is being returned? I'm confused why the borrowed value doesn't live longer. Sorry to bother you with a newb question, but I would appreciate any help. Thanks!

**Comment by fdehau** [comment]
Hi, this is actually not an obvious problem so you should not worry about asking questions ;). First, widgets were designed as views that you apply to your data instead of data containers, so most of the time they don't take ownership of the things you want them to render. A consequence of this is that most of them are constructed using the non-consuming builder pattern (https://doc.rust-lang.org/1.0.0/style/ownership/builders.html). This has already been reported as problematic there #28 and I'm considering changing them to consuming builder pattern as they would allow code as the one you attempted to write.

However, I would emphasize that you should not have to store widgets. This is an immediate library so you should call them when you need to render to the terminal. If you want to create a CPU widget I would suggest that you implement the Widget trait where you can rely on existing widgets or simply put your own logic.

**Comment by cjbassi** [comment]
Thanks for the info! Got everything working now by implementing Widget for CPU.
