### ISSUE TITLE
SelectableList with no item selected

### ISSUE THREAD

**Issue by anowlcalledjosh** [fdehau/tui-rs#68]
Two things:

1.  It seems like a `SelectableList` will always show its `highlight_symbol` next to one of its items even if none of the items are selected, whereas the `highlight_style` is only applied when an item is actually selected.

2.  I (a total Rust newbie) can't work out a good way to conditionally select an item in a `SelectableList`... I think if `SelectableList.select` took an `Option<usize>`, everything would all just work, but since it takes just a `usize`, I have to only call `.select` if some condition is true, which means I have to do something ugly like this:

    ```rust
    let mut w = tui::widgets::SelectableList::default();
    let w = w.block(Block::default().borders(Borders::ALL))
        .items(&["one", "two", "three"])
        .highlight_style(tui::style::Style::default().fg(tui::style::Color::Cyan));
    if let Some(n) = app.selected {
        w.select(n)
    } else {
        w
    }.render(t, &chunks[0]);
    ```

    Is there (or could there be added) a better way to deal with conditional selection?

**Comment by fdehau** [comment]
Hi your issue is closely related to #28. The last release of this crate (a beta version for now) should fix both of your issues. First the highlight symbol is now hidden when nothing is selected. Secondly, `select` on `List` takes an `Option<usize>` . Moreover, widget builders are now consumables (ie they take ownership) so your example should be simpler to implement.
