### ISSUE TITLE
Multiple selections in a Table

### ISSUE THREAD

**Issue by kivimango** [fdehau/tui-rs#681]
## Problem
Hello ! I just noticed that i can't select multiple items in a Table, only a single item is allowed.

## Solution
Implement code for allowing multiple selection of items in a Table.
I see an open PR regarding this problem with List too,
the work could be based on that with little modification.

**Comment by fritzrehde** [comment]
I am working on a project using `tui-rs` called [`watchbind`](https://github.com/fritzrehde/watchbind). I wanted this exact feature as well, but since the development on `tui-rs` seems to have halted, I thought I would just create my own version that is not general but tailored to my use-case. You can find the code [here](https://github.com/fritzrehde/watchbind/blob/main/src/state.rs). More specifically, the `set_lines`, `get_selected_lines` and `draw` methods are probably most interesting for you there.
I thought I would just post this here for other people looking for inspiration. Hope it helps!
