### ISSUE TITLE
 Ctrl-C

### ISSUE THREAD

**Issue by aep** [fdehau/tui-rs#76]
catching sigint is a bit strange UX. (good old quit vim jokes anyone?)
that might be an unintentional side effect of terminal raw mode,
so i it would be ok to add a keyhandler for ctrl+c i guess, but Event::Input lacks a modifier.

**Comment by Catvert** [comment]
Hi,
I managed to have the ctrl + c in my application, to do that, it's as simple as that:
```rust
 if let Key::Ctrl('c') = input {
   break; // Break the ui loop (same as 'q' in examples)
}
```

**Comment by fdehau** [comment]
As mentioned on the README, this crate does not provide any input handling directly since it is usually provided by the terminal backend you choose. Thus you may refer to those crates for how sigint may be handled.

I know that the examples might not be the best illustration of this fact as they include a fair amount of input handling. But this is done for the sake of having a more dynamic content. Therefore `Event` is just a convenient way of dealing with different source of events but it is not part of the crate directly (defined inside this [file](./examples/util/event.rs)).

Closing this since @Catvert has proposed a valid solution IMO
