### ISSUE TITLE
Type hell

### ISSUE THREAD

**Issue by jrmiller82** [fdehau/tui-rs#84]
Maybe I'm just too new to rust; but it sure is damn hard with the beta of the library to break a drawing step into a separate function. Compiler puke everywhere trying to  figure out the damn types. Like to pass a terminal to a function it has to be `t: &mut Terminal<TermionBackend<RawTerminal<io::Stdout>>>`. And I can't figure out what the return value should be on a `t.draw(some closure)?;` call...

**Comment by jrmiller82** [comment]
Apparently the return value should be as simple as a `Result<(), Error>`...

**Comment by fdehau** [comment]
I agree that the type definition for a simple terminal can be a bit overwhelming at first. I choose to let people provide their own instance of the backend when creating the `Terminal` interface. Thus the long type signature.

However, you could use either use a type alias or change your functions to be generic over a backend (as I did in https://github.com/fdehau/tui-rs/commit/f6d2f8f929b97ecb75c9cd1e7321b53f70fc390a) in order to reduce the type complexity.

Most of the functions return an `io::Result<_>`
