### ISSUE TITLE
How do we control the cursor display?

### ISSUE THREAD

**Issue by jrmiller82** [fdehau/tui-rs#91]
I don't see anything in the docs about how to control the cursor. I'd be happy to submit documentation PR, except I have no clue how to control the cursor.

**Comment by jrmiller82** [comment]
Ok, looks like we need the terminal field of a tui::Frame to be public if we're going to follow the 

`t.draw(|mut f| { ... }` structure because now you can't access the terminal inside the closure with `f.terminal` since the `terminal` field is private. 

Thoughts?

**Comment by Minoru** [comment]
@fdehau Is it okay to add `Frame::show_cursor()` and `Frame::hide_cursor()`? These should call the same methods on the underlying `Terminal`. I believe this won't interfere with the rest of the rendering. The reason I'm asking for this is because I want to implement an input field, and I currently can't display a cursor from inside the drawing function.

I'll submit a PR if you're okay with the idea.

**Comment by Minoru** [comment]
Sorry, I commented too hastily. Turns out for an input field, I also want to force tui-rs to put the cursor at the end of the input field. This happens automatically in some cases, but I believe I can't count on that in general. Consider my previous offer withdrawn.

**Comment by fdehau** [comment]
@Minoru Isn't the behavior shown in the user_input example what you want ?

**Comment by Minoru** [comment]
It is, @fdehau, it's just that it's inconvenient to do right now: instead of doing it at the time of rendering, I have to store the desired position and act on it later, after all the drawing is done. I think that's exactly what you meant by "ergonomics … is not ideal", I think.

Actually, can't `Frame` have a field like `Option<(u16, u16)>`, which is the cursor's desired position after drawing the frame? `None` means the cursor is hidden, `Some` with a position means the cursor is shown and is positioned at the given cell.

**Comment by fdehau** [comment]
@Minoru That's a very good compromise. I would gladly accept a PR for that.

**Comment by Minoru** [comment]
Cool! Working on it.
